<?
 $classpath = array (
  'Inc_Authen' => '../../framework/include/authen.inc.php',
  'Inc_Autoresponder' => '../../framework/include/autoresponder.inc.php',
  'Inc_Browser' => '../../framework/include/browser.inc.php',
  'Inc_CrossDomain' => '../../framework/include/crossdomain.php',
  'Inc_Debug' => '../../framework/include/debug.inc.php',
  'Inc_External' => '../../framework/include/external.php',
  'Inc_GeoIP' => '../../framework/include/geoip.php',
  'Inc_Htmlutil' => '../../framework/include/htmlutil.inc.php',
  'Inc_Image' => '../../framework/include/image.inc.php',
  'Inc_Io' => '../../framework/include/io.inc.php',
  'Inc_Locale' => '../../framework/include/locale.inc.php',
  'Inc_Log' => '../../framework/include/logger.inc.php',
  'Inc_Mailer' => '../../framework/include/mailer.inc.php',
  'Inc_PHPMO' => '../../framework/include/phpmo.inc.php',
  'Inc_Pngfix' => '../../framework/include/pngfix.inc.php',
  'Inc_PostTrack' => '../../framework/include/posttrack.php',
  'Inc_Secur' => '../../framework/include/secur.inc.php',
  'Inc_Server' => '../../framework/include/server.inc.php',
  'Inc_SessionCache' => '../../framework/include/sessioncache.php',
  'Inc_SQL' => '../../framework/include/sql.php',
  'Inc_Var' => '../../framework/include/var.inc.php',
  'Inc_WkToImage' => '../../framework/include/wktoimage.php',
  'Inc_ZipUtil' => '../../framework/include/ziputil.inc.php',
);