<?

class Inc_Browser{
			
	 
	//
	//
	//
	//
	//
	// DO NOT EDIT THIS FILE WHILE REWRITE DEVELOPMENT PLEASE EDIT IN /tmp/include_src 
	//
	//
	//
	//
	//
	public static function checkIsIE(){
		$regie='/msie\s(5\.[5-9]|[6]\.[0-9]*).*(win)/i';
		$retVal = isset($_SERVER['HTTP_USER_AGENT']) &&
			preg_match($regie,$_SERVER['HTTP_USER_AGENT']) &&
			!preg_match('/opera/i',$_SERVER['HTTP_USER_AGENT']);
		return $retVal;
	}
	
	//
	//
	//
	//
	//
	// DO NOT EDIT THIS FILE WHILE REWRITE DEVELOPMENT PLEASE EDIT IN /tmp/include_src 
	//
	//
	//
	//
	//
	
	public static function recordLogin($memberObj,$custom=''){
		include_once prepath()."../lib/browser_detection.php";
	
		$logdir = prepath()."../log/login/".date('Y-m');
		if(!file_exists($logdir)){
			mkdir($logdir,0777,true);
		}
	
		$browserAR = browser_detection( 'full_assoc' );
		$browserAR['custom'] = $custom;
		
		$logfile = $logdir.'/'.'login_'.date('Y-m-d').'.log';
		$loghandle = fopen($logfile,"a+");	
		
		fwrite($loghandle, date('Y-m-d H:i:s')."\t");
		fwrite($loghandle, $memberObj->email."\t".Inc_Server::real_ip()."\tJSON");
		fwrite($loghandle, json_encode($browserAR)."\t");
		fwrite($loghandle, "\n");
	
		fclose($loghandle);
		
	}
	
	
		
}