<?
exit("no more");
//include "../../framework/core/common.inc.php";
function prepath()
{
	$prepath = "";
	$cwdtext = getcwd();
	$cwdtext = str_replace("\\","/",$cwdtext);
	$cwd = explode("/",$cwdtext);
	//var_dump($cwd);
	if($cwd[count($cwd)-1]!='index' && $cwd[count($cwd)-1]!='model' && $cwd[count($cwd)-1]!='control' && $cwd[count($cwd)-1]!='log' && $cwd[count($cwd)-1]!='compiler'){
		$prepath = "../";
	}
	return $prepath;
}

function Rewrite_Include($path,$exception=NULL){
	$rstext = "// DO NOT EDIT THIS FILE WHILE REWRITE DEVELOPMENT PLEASE EDIT IN /tmp/include_src \n";
	echo "{$path}<br />";
	$dir_handle = @opendir($path) or die("Unable to open $path");
	if($exception==NULL){
		$exception=array();
	}
	
	$outputdir = $path;//."_output";
	if(!file_exists($outputdir)){
		mkdir($outputdir);
	}
	
	$countf = 0;
	while ($file = readdir($dir_handle)) 
	{
		if(is_dir($path."/".$file)){
			if(!in_array($file,$exception) && $file !="." && $file !=".." && $file != ".svn"){
				Rewrite_Include($path."/".$file);
			}
			continue;
		}
		if(in_array($file,$exception)){
			continue;
		}

		$class = explode(".",$file);
		if($class[count($class)-1]!="php")continue;
		
		$code = file_get_contents($path."/".$file);
		
		$code = str_replace("\r\n","\n",$code);
		$classname = strtoupper($class[0][0]).substr($class[0],1);


		$classcode = $code;
		$initcode = "";
		if(preg_match('/\/\/\+INIT.+\/\/\-INIT/s', $classcode, $matches)){
			$classcode = str_replace($matches[0],"",$classcode);
			$initcode = $matches[0]."\n";
		}

		$classcode = preg_replace("/^<\?(php)?/is","",$classcode);
		$classcode = preg_replace("/\n/","\n\t",$classcode);
		$classcode = preg_replace("/function /","//\n\t//\n\t//\n\t//\n\t//\n\t".$rstext."\t//\n\t//\n\t//\n\t//\n\t//\n\tpublic static function ",$classcode);

		$classcode = "\n{$initcode}class Inc_$classname{
			".$classcode."
		\n}";

		$rwcode = "\ninclude_once '../framework/include/".$class[0].".inc.php';\n";
		
		
		preg_match_all('/.*(function)[\t ]+(.+?)\((.*)\)/i', $code, $matches);
		for($i=0;$i<count($matches[0]);$i++){	
			$is_repeat = true;
			$rwcode.="if(!function_exists(".$matches[2][$i].")){\n\t";
			$rwcode.= $matches[1][$i];
			$rwcode.= " ".$matches[2][$i]."(";
			$rwcode.= "".$matches[3][$i]."){\n\t\treturn Inc_$classname::{$matches[2][$i]}(";
			$params = $matches[3][$i];
			
			preg_match_all('/\$[\w\d_]+/i', $params, $mp);
			$paramAr = array();
			for($j=0;$j<count($mp[0]);$j++){	
				$paramAr[] = $mp[0][$j];
			}
			$rwcode.= implode(",",$paramAr);
			$rwcode.= ");\n";
			$rwcode.= "\t}\n}\n";
		}
		$rwcode.= "";
		echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{$file}<br />";

		//var_dump($rwcode);
		//var_dump($classcode);
		$restrict = "<?\n";
		for($i=0;$i<20;$i++){
			if($i%2==0){
				$restrict .= "// ------------------------------------------------------------------------------- \n";	
			}else{
				$restrict .= $rstext;
			}
		}
		
		
		
		$fw = file_put_contents("../include/".$file,$restrict.$rwcode);
		$fw = file_put_contents("../framework/include/".$file,$restrict.$classcode);
		//exit();
		include_once "../include/".$file;
	}
	
	closedir($dir_handle);
}

$except = array("common.inc.php","func.inc.php","config.inc.php","csql.php","unittest.inc.php","wordpress.inc.php","ziputil.inc.php");
Rewrite_Include("../tmp/include_src",$except);


