<?php
define("T_LOGOUT","Logout");
define("T_LOGIN","Login");
define("T_USERNAME","Username");
define("T_PASSWORD","Password");
define("T_DASHBOARD","Dashboard");
define("T_ORDER","Order");
define("T_PROFILE","Profile");
define("T_DOCTOR","Doctor");
define("T_PATIENT","Patient");
define("T_QLAUNCH","Quick launch");
define("T_DRAFT","Draft");
define("T_SEND","Sending");
define("T_HEXA","At Hexa");
define("T_ACCOUNT","Account");
define("T_SENDBACK","Delivery");
define("T_PROCESS","Process");
define("T_OVERVIEW","Overview");
define("T_HISTORY","History");
define("T_COST","Cost");
define("T_TPRINT","Print"); //Can't use T_PRINT
define("T_EDIT","Edit");
define("T_SUBMIT","Submit");
define("T_SAVE","Save");
define("T_LABNAME","Lab. Name");
define("T_ADDRESS","Address");
define("T_PROVINCE","Province");
define("T_COUNTRY","Country");
define("T_SENDING","Sending");
define("T_BILLING","Billing");
define("T_CPFA","Copy from address");
define("T_NFORDER","Not found any order");
define("T_ORDERCODE","Order Code");
define("T_NOTE","Note");
define("T_TYPEOFWORK","Type of work");
define("T_SMITDATE","Submit date");
define("T_ARRVDATE","Arrive date");
define("T_SENTDATE","Sent date");
define("T_STATUS","Status");
define("T_STARTDATE","Start date");
define("T_ENDDATE","End date");
define("T_EXPIRE","Expire");
define("T_WARANTY","Waranty");
define("T_POSTNEW","Posted In: News by Administrator");
define("T_ADDDOCTOR","To add doctor: ");
define("T_FILLNAME","Fill name and click +");
define("T_LANGUAGE","Language");
define("T_MORE","more..");
define("T_CUSTNAME","Customer name");
define("T_CUSTNICK","Customer nick");
define("T_CHOOSEONE","Choose one");
define("T_ACCEPT","Accept");
define("T_CHECK","Check");
define("T_STEP","Step");
define("T_AGREEMENT","Agreement");
define("T_UREGISTER","User register");
define("T_INFOMATION","Infomation");
define("T_FINISH","Finish");
define("T_DISCLAIMER","Disclaimer");
define("T_MSG001"," Please review the following terms and indicate <br />          your agreement  		below.");
define("T_IAGREE","I agree.");
define("T_INAGREE","I do not agree.");
define("T_NEXT","Next");
define("T_AGAIN","again");
define("T_MSG002","Beta testing version allow only user in thailand (just for now).");
define("T_REMARK","Remark");
define("T_EMAIL","Email");
define("T_TEL","Tel");
define("T_STATEPROVINCE","State/Province");
define("T_HCName","Hospital / Clinic name");
define("T_ROAD","Road");
define("T_DISTRICT","District");
define("T_SUBDISTRICT","Subdistrict");
define("T_MOO","Moo");
define("T_SOI","Soi");
define("T_MSG003","Thank you for register.<br />          We will verify your account in 2~3 working days<br />          for match your information with our site that we have<br />          then you can get all of your order history.</p>");
define("T_DONE","done");
define("T_REGISTRATION","Registration");
define("T_REGISNEW","Register new account");
define("T_ALPHANUMERIC","Alphanumeric letters");
define("T_RE_PASSWORD","Retype password");
define("T_RE_EMAIL","Retype e-mail address");
define("T_SHIPPING","Shipping");
define("T_REGISTER","Register");
define("T_CANCEL","Cancel");
define("T_REGUSRnPSSW","Register your user &amp; password");
define("T_EXISTACCOUNT","You already have user account store in database.");
define("T_CONTACT","Please contact Supporter.");
define("T_EMAILADDR","E-mail address");
define("T_TELNO","Telephone no");
define("T_BTMAINPAGE","Back to main page");
define("T_FILLALLTEXT","Please fill in all text box.");
define("T_INCORRECTPASSWORD","Password and retype password mismatch.");
define("T_INCORRECTEMAIL","E-mail and retype e-mail mismatch.");
define("T_EMAILINVALID","E-mail validation failed. The e-mail you fill in text box is invalid.");
define("T_DUPLICATEUSERNAME","Duplicate username.");
define("T_COMPLETED","Completed");
define("T_YR_USR_IS","Your username is");
define("T_YR_PSSW_IS","Your password is");
define("T_NOTEUSERANDPASS","Please note your username and password and keep it secretly.");
define("T_GTLOGINPAGE","go to Login page");
define("T_SELECT","Select");
define("T_NCUSTOMER","new customer");
define("T_SEARCH","Search");
define("T_FIND","Find");
define("T_INPUTDRNAME","Input doctor name");
define("T_NODOCTOR","No Doctor name store in database.");
define("T_AUTHENFAIL","Authentication failed.");
define("T_PRICE","Price");
define("T_N","X");
?>